audit_header: false
title: San Diego Real Estate Video Blog with Stacey Anistacia Miller
description: Our mission at Big Block Realty is to be your best resource for San Diego real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Big Block Realty, your professional San Diego Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Stacey Anistacia Miller
  title:
  license_number:
  about_markdown: |
    Previously a founder and  the owner of 4 successful companies in the high end fashion industry. 23 years of experience as a top selling Real Estate Agent. Certified Bank Owned Property Specialist, Luxury Agent Certified, Certified Global Property Specialist. Awarded a top 10% of all sales agents nationwide award as per the Board of Realtors. My list to sale price averages 96% helping me to create strong lifetime relationships with clients  Expertise in real estate across the board – from luxury property sales to management of ROE property sales. Strong focus and expertise in luxury home sales for over 20 years. Extensive experience in team management and personnel training of the sales agents.
  market: San Diego
  brand: Big Block Realty
  brokerage:
  address: '2820 Camino Del Rio S #314<br>San Diego, CA 92108'
  phone: 619-393-6633
  phone_type:
  phone2:
  phone2_type:
  email: stacey@staceymiller.com
  url: http://www.staceymiller.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.realtor.com/propertyrecord-search
  second_CTA_text: Home Search
  second_CTA_URL: http://www.staceymiller.com/properties/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your San Diego Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.realtor.com/propertyrecord-search

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a San Diego Home?"
    CTA_text2: "Search the entire MLS for your San Diego home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.staceymiller.com/properties/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: true
  facebook_url: https://www.facebook.com/StaceyAnistaciaMillerSDRealtor
  linkedin_url: https://www.linkedin.com/in/staceyanistaciamiller/
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/AgentStaceyMiller/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'San Diego Real Estate Podcast with Stacey Anistacia Miller'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the San Diego Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Big Block Realty - your professional San Diego Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Diego, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Stacey Anistacia Miller'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: San Diego Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#58bb47'
  theme_color: '#231f20'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
